#!/bin/sh /etc/rc.common

USE_PROCD=1

START=20
STOP=89

PROG=/usr/sbin/vxlan-ipv6-sanitize
CONF=vxlan-ipv6-sanitize

start_service() {
	local verbose

	config_load "$CONF"
	config_get_bool verbose main verbose 0

	procd_open_instance
	procd_set_param command "$PROG"
	[ "$verbose" -eq 1 ] && procd_append_param command -v
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
